[profile.default]
# forge config
verbosity = 3
fs_permissions = [{ access = "read", path = "./script/input"}]
# Solidity config.
solc-version = "0.8.22"
evm_version = "paris" # Needed to deploy on chains that don't support PUSH0 (e.g. Optimism, Arbitrum)
optimizer = true
optimizer-runs = 10_000_000
bytecode_hash = "ipfs"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts", # Needed for UMA protocol imports.
  "@chainlink/=lib/chainlink/",
]

[profile.ci.fuzz]
runs = 1000

[profile.default.fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = true
ignore = [
  "src/lib/SafeTransferLib.sol",
  "src/interfaces/OptimisticOracleV2Interface.sol"
]